ctblog/blog/urls.py
from django.urls import path
from .views import home_page, contact_us, blog_detail
app_name = "blog"

urlpatterns = [
    path("",home_page, name="home"),
    path("contact-us", contact_us,name="contact-us"),
    path("blog-detail/<int:pk>/", blog_detail, name="blog-detail"),
]

ctblog/ctblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ctblog/blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to="blog_posts/", default=None, null=True, blank=True)

    def __str__(self):
        return self.title
    

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name + " -"+ self.last_name
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name="blog_comment", on_delete=models.CASCADE)
    name = models.CharField(max_length = 255)
    message = models.TextField()


    def __str__(self):
        return self.blog.title + " -"+ self.message

ctblog/blog/forms.py
from django import forms
from .models import Contact, Comment


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = "__all__"

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ["blog"]

ctblog/blog/views.py
from django.shortcuts import render, HttpResponse
from .models import Blog, Contact
from .forms import ContactForm, CommentForm, Comment

# Create your views here.

def home_page(request):
    context = {}
    blogs = Blog.objects.all()
    context["blogs"] = blogs
    return render(request, "home.html", context)

def contact_us(request):
    context = {}
    if request.POST:
        my_form = ContactForm(request.POST)
        if my_form.is_valid():
            my_form.save()
        else:
            context["errors"] = my_form.errors
        

        # new_contact = Contact.objects.create(
        #     first_name = request.POST['first_name'],
        #     last_name = request.POST['last_name'],
        #     email = request.POST['email'],
        #     message = request.POST['message']
        # )

    return render(request, "contact_us.html", context)



def blog_detail(request, pk):
    context = {}
    blog = Blog.objects.get(id=pk)
    context["blog"] = blog

    if request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            obj = comment_form.save(commit=False)
            obj.blog = context["blog"]
            obj.save()
        else:
            context["errors"] = comment_form.errors
    
    comments = Comment.objects.filter(blog = context['blog'])
    context['comments'] = comments
    return render(request, "blog_detail.html", context )
    

ctblog/blog/templates/base.html
<html lang="en">
    {%load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CTBLOG Homepage</title> 
    <link rel="stylesheet" href="{%static 'style.css'%}"> 


</head>
<body>
    <header>
        <nav>
            <ul class="nav-el">
                <li><a href="{%url 'blog:home'%}">Home Page</a></li>
                <li><a href="{%url 'blog:contact-us'%}">Contact Us</a></li>
                <li><a href="">About Us</a></li>
            </ul>
        </nav>
    </header>
    <br>
    {%block content%}
    
    {%endblock%}

    <script src="{%static 'js/main.js'%}"></script>
    
</body>
</html>

ctblog/blog/templates/blog_detail.html
{%extends "base.html"%}

{%block content%}
<h1>{{blog.title}}</h1>
{%if blog.image%}
<img width="300px" src="{{blog.image.url}}" alt="">
{%endif%}


<p>{{blog.description}}</p>
<h3>Comments</h3>

{%for comment in comments%}
<p><b>{{comment.name}}</b></p>
<p>{{comment.message}}</p>
<hr>

{%endfor%}

{%if errors%}
{{errors}}
{%endif%}

<form action="" method="POST">
    {%csrf_token%}
    <label for="">Name</label>
    <input type="text" name="name">
    <br>

    <label for="">Message</label>
    <textarea name="message" id="" cols="30" rows="10"></textarea>
    <br>

    <button>Submit</button>

</form>
{%endblock%}

ctblog/blog/templates/contact_us.html
{%extends "base.html"%}

{%block content%}
<h1>Welcome to Contact Us Page</h1>
{%if errors%}
{{errors}}
{%endif%}

<form method="post" action="">{%csrf_token%}
    <label for="">First Name</label>
    <input type="text" name="first_name" id="">
    <br>
    <label for="">Last Name</label>
    <input type="text" name="email" id="">
    <br>
    <label for="">Email</label>
    <input type="text" name="last_name" id="">
    <br>
    <label for="">Message</label>
    <textarea name="message" id="" cols="30" rows="10"></textarea>
    <br>
    <button>Submit</button>
    
    
</form>
{%endblock%}

ctblog/blog/templates/home.html
{%extends "base.html"%}

{%block content%}
<h1>Welcome to CT Blog Home Page</h1>
{%for blog in blogs%}
<p><a class="post-title" href="{%url 'blog:blog-detail' pk=blog.id %}">{{blog.title}}</a></p>
<hr>
{%endfor%}
{%endblock%}